[package]
name = "pcre2-binding-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["pcre2-sys"]

[dependencies]
libc = "0.2.0"
pcre2-sys = { version = "0.1.0", path = "pcre2-sys" }